export const DESIGNS_PAGE_OPEN = 'DESIGNS_PAGE_OPEN';
export const DESIGNS_PAGE_DATA_RECEIVE = 'DESIGNS_PAGE_DATA_RECEIVE';

export const DESIGNS_PAGE_GET_BATCH_DATA = 'DESIGNS_PAGE_GET_BATCH_DATA';
export const DESIGNS_PAGE_BATCH_DATA_RECEIVE = 'DESIGNS_PAGE_BATCH_DATA_RECEIVE';

export const DESIGNS_PAGE_RESET_DATA = 'DESIGNS_PAGE_RESET_DATA';
